### ISSUE TITLE
Colored Glider

### ISSUE THREAD

**Issue by ghost** [mt-mods/hangglider#12]
Dyeing Hangglider in "dark_green" and "dark_grey" turns the Hangglider in a white "Colored Gilder" instead of darkgreen and darkgrey, every other color is working.

**Comment by Niklp09** [comment]
Confirmed, seems to work w/ unifieddyes

**Comment by Abso0ProgSkills** [comment]
Well, I'm not using unifieddyes.
And I noticed that Black Glider is Pitch Black.

That's all.

**Comment by OgelGames** [comment]
Simple bug, `%w` doesn't match underscores :P Fixed.
